version: '3.8'

services:
  splunk:
    image: splunk/splunk:9.1
    container_name: splunk
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme123
    ports:
      - "8000:8000"
      - "8088:8088"
      - "9997:9997"
    volumes:
      - splunk-data:/opt/splunk/var

  test-linux:
    build:
      context: .
      dockerfile: Dockerfile.uf-test
    container_name: test-linux
    platform: linux/amd64
    depends_on:
      - splunk
    tty: true

volumes:
  splunk-data:
