
version: '3.7'

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000"   # Web interface
      - "8088:8088"   # HTTP Event Collector
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    volumes:
      - splunk-data:/opt/splunk/var

volumes:
  splunk-data:
